[programs.devnet]
myepicproject = "Dt8bpxueHcsn35VdN1EoYgFCaS2tJcP7YodZyMMby6Se"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/robin/.config/solana/id.json"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "node tests/myepicproject.js"

